include:
  - component: $CI_SERVER_FQDN/quiqqer/stabilization/ci-cd-components/quiqqer-package-bundle/quiqqer-package-bundle@main
    inputs:
      php-82: true
      php-83: true
      php-84: true
      php-85: true

upgrade-tests-php8.5:
  extends: phpunit-php8.5
  script:
    - !reference [phpunit-php8.5, script]
    - ./tools/phpunit --configuration phpunit.upgrade.xml --cache-directory "${PHPUNIT_CACHE_DIRECTORY}-upgrade"
